### ISSUE TITLE
Is this a standard license?

### ISSUE THREAD

**Issue by rugk** [V-Sense/DeepNormals#2]
…or is this actually a self-written once?

Just curious…

**Comment by MatisHudon** [comment]
Hi, 

It is a modified version of a commonly used example that may be based on a standard template.

**Comment by rugk** [comment]
Could you be a little more explicit, i.e. what example/what standard?

**Comment by MatisHudon** [comment]
You can find similar examples in the following projects:

[https://github.com/thmoa/videoavatars](https://github.com/thmoa/videoavatars)
[https://github.com/davidstutz/extended-berkeley-segmentation-benchmark](https://github.com/davidstutz/extended-berkeley-segmentation-benchmark)
[https://github.com/davidstutz/probabilistic-pca](https://github.com/davidstutz/probabilistic-pca)
[https://github.com/davidstutz/hierarchical-graph-based-video-segmentation](https://github.com/davidstutz/hierarchical-graph-based-video-segmentation)

other examples:

[https://github.com/TadasBaltrusaitis/OpenFace/blob/master/OpenFace-license.txt](
https://github.com/TadasBaltrusaitis/OpenFace/blob/master/OpenFace-license.txt)
[https://github.com/bobbens/sketch_simplification/blob/master/LICENSE](https://github.com/bobbens/sketch_simplification/blob/master/LICENSE)

**Comment by rugk** [comment]
The last two ones seems to be different ones, but for the other ones [I've asked here](https://opensource.stackexchange.com/questions/7687/what-non-commercial-license-is-that) what that may be.

**Comment by MatisHudon** [comment]
Thank you for this, the OMNeT++ license appears to be more complete.
