### ISSUE TITLE
Training an Image

### ISSUE THREAD

**Issue by JuHyung-Son** [V-Sense/DeepNormals#6]
When training, did you train every tile of an image among 420 images or just a random tile among 84000 tiles?

**Comment by MatisHudon** [comment]
If I understand your question correctly: Random tile among 84000, we generated a tfrecord file containing all tiles (20 tiles per image), then used the shuffle batch during training. 
Contact me by email if you need more info or the tfrecord file directly. (hudonm@scss.tcd.ie)
