### ISSUE TITLE
run Docker image clarification

### ISSUE THREAD

**Issue by gbernal** [V-Sense/DeepNormals#9]
Hi @MatisHudon I'm trying to follow the direction for running the docker image, but I'm a bit new to docker and I was hoping you could clarify the arguments for the paths. I'm running it like this

` sudo nvidia-docker run -v /PycharmProjects/DeepNormals:/var/lib/docker -it matishudon/dockerdeepn python3 /PycharmProjects/DeepNormals/main.py --docker_path /var/lib/docker `

But when running it I get the error ` python3: can't open file '/PycharmProjects/DeepNormals/main.py': [Errno 2] No such file or directory`

Could you please help, thank you in advance!

**Comment by MatisHudon** [comment]
Hi, 
`container/directory/` is a directory on the container and not on the local machine, this part of the command:  `CodeDirectory/:/container/directory/` will 'mount' your local directory `/PycharmProjects/DeepNormals` at `/container/directory/` on your docker container. 

Hope this help.

**Comment by gbernal** [comment]
Hi @MatisHudon thank you for your quick response. It sounds like I should be just running the command line as is from the instruction given in the read me file `sudo nvidia-docker run -v CodeDirectory/:/container/directory/ -it matishudon/dockerdeepn python3 /container/directory/main.py --docker_path /container/directory/
`
When I do that I get this error

`docker: Error response from daemon: create CodeDirectory/: "CodeDirectory/" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
`
Thanks once again

**Comment by MatisHudon** [comment]
Relace `CodeDirectory/` with `/PycharmProjects/DeepNormals`

**Comment by gbernal** [comment]
Thank you @MatisHudon it works now. I got it working like this 
`sudo nvidia-docker run -v /home/PycharmProjects/DeepNormals/:/container/directory/ -it matishudon/dockerdeepn python  /container/directory/main.py --docker_path /container/directory/` it case it helps someone else
